services:

  app:
    container_name: app # Renamed
    image: nextcloud:fpm
    restart: always
    environment:
      - NEXTCLOUD_ADMIN_USER=NEXTCLOUD_ADMIN_USER # CHANGE THIS!
      - NEXTCLOUD_ADMIN_PASSWORD=NEXTCLOUD_ADMIN_PASSWORD # CHANGE THIS!
      - MYSQL_DATABASE=nextcloud # Added
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=MYSQL_PASSWORD
      - MYSQL_HOST=db
      - SKIP_DOMAIN_VALIDATION=true # Added
    expose:
      - '80'
      - '9000'
    volumes:
      - app_data:/var/www/html
      - ./www.conf:/usr/local/etc/php-fpm.d/www.conf # Added
  db: # Added
    image: mariadb:10.6
    restart: always
    command: --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=MYSQL_ROOT_PASSWORD
      - MYSQL_PASSWORD=MYSQL_PASSWORD
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
  onlyoffice-document-server:
    container_name: onlyoffice-document-server
    image: onlyoffice/documentserver:latest
    restart: always
    environment:
      - JWT_SECRET=secret
    expose:
      - '80'
      - '443'
    volumes:
      - document_data:/var/www/onlyoffice/Data
      - document_log:/var/log/onlyoffice
  nginx:
    container_name: nginx-server
    image: nginx
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - app_data:/var/www/html
volumes:
  document_data:
  document_log:
  app_data:
  mysql_data:
  db: # Added